<<<<<<< HEAD
// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var base = require('./webpack.config');

base.output.publicPath = '';

base.entry = {
  index: [
    path.resolve(__dirname, './public/js/main.jsx')
  ],
  edit: [
    path.resolve(__dirname, './public/js/edit.jsx'),
  ]
},


base.plugins = [
  new webpack.DefinePlugin({
    env: {
      isDevelopment:false
    }
  }),
  new webpack.optimize.UglifyJsPlugin({
    compress:{
      warnings:false
    }
  })
];

module.exports = base;
=======
var basicConfig = require('./webpack.config');

var definePlugin = new webpack.DefinePlugin({
  env:{
    isDevelopment:false
  }
});



var uglify = new webpack.optimize.UglifyJsPlugin({
  compress:{
    warnings:false
  }
});

basicConfig.plugins.push(uglify);
>>>>>>> origin/master
