// Generated by CoffeeScript 1.8.0
(function() {
  var path, webpack, webpackDevPort;

  path = require('path');

  webpack = require('webpack');

  webpackDevPort = 7301;

  module.exports = {
    webpackDevPort: webpackDevPort,
    resolve: {
      extensions: ['', '.js']
    },
    entry: {
      homeIndex: path.resolve(__dirname, './public/js/home/index/z-main.js'),
      listIndex: path.resolve(__dirname, './public/js/home/list/z-main.js')
    },
    output: {
      path: path.resolve(__dirname, './public/js/dist/'),
      publicPath: "http://localhost:" + webpackDevPort + "/public/js/dist",
      filename: '[name].js'
    },
    module: {
      loaders: [
        {
          test: /\.ejs$/,
          loader: 'ejs-loader?variable=data'
        }
      ]
    },
    devtool: 'source-map'
  };

}).call(this);

//# sourceMappingURL=webpack.config.js.map
