
// Generated by CoffeeScript 1.8.0
(function() {
  var files, fs, jsFileReg, path, policyMap,
    __slice = [].slice;

  path = require('path');

  fs = require('fs');

  policyMap = {};

  jsFileReg = /\.js$/;

  files = fs.readdirSync(path.resolve(__dirname));

  files.filter(function(name) {
    return jsFileReg.test(name);
  }).map(function(nameWithExt) {
    return nameWithExt.replace(jsFileReg, '');
  }).forEach(function(name) {
    return policyMap[name] = require("./" + name);
  });

  module.exports = function() {
    var policy, rest;
    policy = arguments[0], rest = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return policyMap[policy].apply(this, rest);
  };

}).call(this);

//# sourceMappingURL=index.js.map
